### ISSUE TITLE
Share "Download All" "always" fails > 14MB

### ISSUE THREAD

**Issue by hansr** [diodechain/diode_drive_feedback#58] opened 2021-03-21 04:35 UTC
**Environment:** MacOS 10.15.4, dDrive version 1.0.1 // Share download tested on Chrome and Firefox

**Description:**
Diode Drive shares have a "Download All" button that allows all the files in the share to be downloaded as a .zip file.  However, it doesn't work on total size > ~14MB.  It seems to fail every time just before completing.  

**Steps to reproduce:**

1. Create a folder that has at least one file in it 
2. Share the folder
3. Open the share in a browser
4. Click "Download All" and observe problem
5. Click "Download" on one of the files, even if >14MB, and observe the lack of problem

Here are two shares that exhibit this problem:
a) single file over 16MB: https://drive-raq8rki48b9so2g3f7ym.diode.link/za08z6nkqtkhoky4
b) multiple files each ~2.7MB totaling over 16MB: https://drive-raq8rki48b9so2g3f7ym.diode.link/7tpji8gynhp7t5li

Desired behavior:
Step 4 should work like Step 5 (Download All should complete successfully)

**Comment by dominicletz** [comment] 2021-03-24 16:25
@hansr those should succeed, maybe you can send me an error log from one of the failures. ATM I can't reproduce, but I guess it's a relay issue.

On the size, not sure how to solve that -- the zip is being compressed & streamed live, meaning we only know the total size after having sent everything. We could do it twice to get the total size, but then it will take twice as long and will require the sender to copy all the data once into a temporary place.

**Comment by hansr** [comment] 2021-03-31 07:41
@dominicletz I updated the issue to just focus on the download failure.  Since it only happens with the "download all" and not with the "download" - even on just a single file, maybe that is a good clue.  I added links to shares that do this.

Here is some possibly interesting debug.log output (error.log shows nothing).  Note that in 9 times out of 10 failures debug.log also shows nothing - every once in a while it will produce something that looks interesting like this...


15:33:04.814 [debug] Processing with DdriveWeb.ShareZipDownload.index/2
  Parameters: %{"path" => [], "sharecode" => "7tpji8gynhp7t5li"}
  Pipelines: [:browser]
15:33:41.935 [info] CONNECTED TO Phoenix.LiveView.Socket in 108µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "DhQNBxQPEyBTEDJ4IwVfZ2UDBCUWDGcomGjWGPJA5rjMS19TPs3QghQK", "_mounts" => "1", "_track_static" => %{"0" => "https://drive-raq8rki48b9so2g3f7ym.diode.link/css/app-2f8e80b01164a3196b648fd3de9513e0.css?vsn=d", "1" => "https://drive-raq8rki48b9so2g3f7ym.diode.link/js/app-b4b1643ded0c9a900198376514a8dc6a.js?vsn=d"}, "vsn" => "2.0.0"}
15:33:44.022 [info] CONNECTED TO Phoenix.LiveView.Socket in 149µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "BhhVKjoICigrJD9QMWQOAX4KXB4EIFM6eK2ziWSIMFgeAPh2KzkjuDeY", "_mounts" => "1", "_track_static" => %{"0" => "https://drive-raq8rki48b9so2g3f7ym.diode.link/css/app-2f8e80b01164a3196b648fd3de9513e0.css?vsn=d", "1" => "https://drive-raq8rki48b9so2g3f7ym.diode.link/js/app-b4b1643ded0c9a900198376514a8dc6a.js?vsn=d"}, "vsn" => "2.0.0"}

**Comment by dominicletz** [comment] 2021-06-21 13:46
This got fixed with the timeout fix, I can download those file you linked now.

**Closed by dominicletz** 2021-06-21 13:46 UTC
Labels: beta, bug
